# Copyright (c) 2026, YOB and Shayona
"""Build the frontend-facing API reference package.

    bench --site test.localhost execute \
        yob_storefront.tests.fixtures.build_frontend_reference.run

Emits, under ``/tmp/yob_reference_build/reference/api/``:

    openapi.json
    postman_collection.json
    live/README.md
    live/verified-responses.json

Signatures, verbs, guest status and required parameters come from Frappe's own
registry via ``inspect.signature`` -- never from a hand-maintained list, because
a hand-maintained list is what drifts. Payment response examples come from
``capture_payment_contracts``, which executes the real endpoints inside a
rolled-back savepoint with a faked provider.

Verification levels, used honestly:

    wire   -- observed over HTTP through the edge proxy
    test   -- real endpoint executed in-process, savepoint-isolated, provider
              faked; no HTTP round trip and no live provider
    source -- read from the implementation; not executed
"""

import importlib
import inspect
import json
import pathlib
import pkgutil

import frappe

ALLOWED_SITES = {"test.localhost"}
BUILD = pathlib.Path("/tmp/yob_reference_build/reference/api")
PREVIOUS = pathlib.Path("/home/shayona/yob-frontend/reference/api/live/verified-responses.json")
CAPTURED = pathlib.Path("/tmp/yob_payment_contracts.json")

BASE_URL = "http://storefront.local:8080"


# =========================================================
# ENDPOINT INTROSPECTION
# =========================================================

def endpoints():
    found = []
    for app in ("yob_auth", "yob_storefront"):
        pkg = importlib.import_module(f"{app}.api")
        for mod_info in pkgutil.iter_modules(pkg.__path__):
            mod = importlib.import_module(f"{app}.api.{mod_info.name}")
            for name, fn in vars(mod).items():
                if not callable(fn) or not getattr(fn, "__module__", "").startswith(app):
                    continue
                if fn not in frappe.whitelisted:
                    continue
                try:
                    sig = inspect.signature(fn)
                except (TypeError, ValueError):
                    continue
                params = [
                    {"name": p.name,
                     "required": p.default is inspect.Parameter.empty,
                     "default": None if p.default is inspect.Parameter.empty else p.default}
                    for p in sig.parameters.values()
                    if p.name != "auth_context"
                ]
                found.append({
                    "path": f"{app}.api.{mod_info.name}.{name}",
                    "methods": list(
                        frappe.allowed_http_methods_for_whitelisted_func.get(fn) or []
                    ) or ["GET", "POST"],
                    "guest": fn in frappe.guest_methods,
                    "params": params,
                    "summary": (inspect.getdoc(fn) or "").split("\n")[0],
                })
    return sorted(found, key=lambda e: e["path"])


# =========================================================
# PAYMENT DOCUMENTATION (hand-authored semantics, generated examples)
# =========================================================

def _captured():
    if not CAPTURED.exists():
        frappe.throw(
            "Run capture_payment_contracts.run first: payment examples are "
            "generated by executing the endpoints, never hand-written."
        )
    return json.loads(CAPTURED.read_text())


PAYMENT_NOTES = {
    "yob_storefront.api.checkout.proceed_to_payment": [
        "Authenticated. Requires the `sid` session cookie AND `X-Frappe-CSRF-Token`.",
        "Must traverse the edge proxy that sets `X-YOB-Original-Host`; a direct "
        "origin call answers 403 application_access_denied.",
        "No request body. The server derives everything from the session: the "
        "browser never sends amount, currency, cart id or any fingerprint.",
        "201 when a Payment Request was CREATED (first checkout, or a "
        "replacement because the cart changed). 200 when an existing open "
        "obligation was REUSED, with or without a rotated credential.",
        "`payment_url` is a RELATIVE SPA path `/payment/<token>`; the public "
        "payment route must own that path.",
        "The checkout credential expires 1 hour after issue.",
        "A Payment Request's amount and currency are IMMUTABLE once issued. An "
        "unchanged cart reuses the same obligation and the same token; an "
        "expired credential rotates the token on the SAME obligation; a changed "
        "cart issues a REPLACEMENT obligation and revokes the old token "
        "immediately.",
        "Precondition failures, 422 unless noted: cart_not_found (404), "
        "cart_empty, contact_required (field=contact_person), "
        "billing_address_required (field=billing_address), "
        "shipping_address_required (field=shipping_address, only when the cart "
        "is shippable).",
    ],
    "yob_storefront.api.payment.get_checkout_data": [
        "PUBLIC (guest). Authorized solely by the unguessable checkout token.",
        "Serves TWO source shapes. Branch on `data.source_doctype`.",
        "Cart-backed (before payment initiation): source_doctype='Cart', with "
        "`cart`, `contact`, `billing_address`, `shipping_address` objects plus "
        "`cart_updated`, `removed_items`, `price_updated_items`.",
        "Sales-Order-backed (after payment initiation committed the order): "
        "source_doctype='Sales Order', with a flat `items[]`, `order_status`, "
        "`docstatus`, and `billing_address`/`shipping_address` as NAME STRINGS "
        "rather than objects. This shape difference is deliberate and the SPA "
        "must handle both.",
        "After the Payment Request becomes Sales-Order-backed the Cart is no "
        "longer payment truth. It is not read, compared or revalidated, and a "
        "later cart change cannot invalidate the committed payment.",
        "`amount`/`currency` always come from the immutable Payment Request, in "
        "normal business units (e.g. 135.0 INR) -- NOT provider units.",
        "The token is NOT revoked when the source moves Cart -> Sales Order, so "
        "a browser refresh of /payment/:token keeps working and Pay Later "
        "orders remain payable later.",
        "`payment_methods[]` is server-eligible only; render exactly this list.",
    ],
    "yob_storefront.api.payment.process_payment": [
        "PUBLIC (guest). Authorized solely by the checkout token.",
        "The browser sends ONLY `token` and `payment_method`. It never sends "
        "amount, currency, cart, sales order or razorpay order id -- all are "
        "derived server-side from the immutable Payment Request.",
        "`payment_method` is the Payment Method's `name` (e.g. 'Pay Later', "
        "'Razorpay'), i.e. the `name` field from `payment_methods[]` -- not "
        "`method_code`.",
        "Eligibility is re-checked authoritatively on every call. A method that "
        "was offered earlier but is no longer eligible is refused, and no order "
        "is created.",
        "Commits the cart to exactly ONE Draft Sales Order, idempotently. "
        "Repeated calls -- Pay Later then Razorpay, or a retry after failure -- "
        "converge on the same Sales Order and the same provider order.",
        "Razorpay `amount` is in PROVIDER UNITS (paise: 13500 == INR 135.00). "
        "Pay Later `amount` is the normal business amount (135.0). This "
        "difference is intentional: the Razorpay value is passed straight to "
        "the checkout widget.",
        "A provider failure AFTER the local commitment returns "
        "payment_provider_error with `details.retryable = true` and "
        "`details.sales_order`. The Sales Order was NOT rolled back -- do not "
        "show the user 'order failed'; offer a retry.",
    ],
    "yob_storefront.api.payment.verify_payment": [
        "PUBLIC (guest). Authorized by Razorpay's HMAC signature, verified "
        "server-side. NO checkout token is accepted or required: the obligation "
        "is resolved through the provider order id.",
        "All three fields are required; a missing one answers validation_failed "
        "with `field` naming the first missing one.",
        "Idempotent. Re-verifying the SAME payment id returns the same success "
        "body with notice 'Payment already processed.'. A DIFFERENT payment "
        "against an already-settled obligation is refused with "
        "payment_already_processed (409).",
        "Settlement never creates a Sales Order -- it settles the one that "
        "process_payment already committed.",
        "The frontend's claim of success is never trusted; the server "
        "independently fetches and validates the provider order and payment.",
    ],
    "yob_storefront.api.payment_method.get_payment_methods": [
        "Authenticated. Eligibility is centralized server-side; the `customer` "
        "query parameter is accepted for backward compatibility only and is "
        "overwritten with the authenticated Customer (a mismatching value is "
        "rejected outright).",
        "Response is an array of eligible methods ordered by `display_order`, "
        "each with exactly: name, method_code, payment_type, display_order, "
        "icon, description.",
        "`meta.count` carries the number of methods.",
    ],
}

PAYMENT_EXAMPLE_KEYS = {
    "yob_storefront.api.checkout.proceed_to_payment": (
        "proceed_to_payment.created", None),
    "yob_storefront.api.payment.get_checkout_data": (
        "get_checkout_data.cart_backed", "get_checkout_data.stale"),
    "yob_storefront.api.payment.process_payment": (
        "process_payment.razorpay", "process_payment.ineligible_method"),
    "yob_storefront.api.payment.verify_payment": (
        "verify_payment.success", "verify_payment.bad_signature"),
    "yob_storefront.api.payment_method.get_payment_methods": (
        "get_payment_methods", None),
}


# =========================================================
# OPENAPI
# =========================================================

def build_openapi(eps, captured):
    paths = {}

    for ep in eps:
        verb = "post" if "POST" in ep["methods"] else "get"
        dotted = ep["path"]
        success_key, error_key = PAYMENT_EXAMPLE_KEYS.get(dotted, (None, None))

        statuses = {
            "200": {"description": "Success envelope",
                    "content": {"application/json": {
                        "schema": {"$ref": "#/components/schemas/Success"}}}},
            "4XX": {"description": "Error envelope",
                    "content": {"application/json": {
                        "schema": {"$ref": "#/components/schemas/Error"}}}},
        }

        if success_key and success_key in captured:
            body = captured[success_key]
            code = str(body["__http_status__"])
            entry = {"description": "Success envelope",
                     "content": {"application/json": {
                         "schema": {"$ref": "#/components/schemas/Success"},
                         "example": {k: v for k, v in body.items()
                                     if k != "__http_status__"}}}}
            statuses[code] = entry

        # proceed_to_payment answers 201 on creation and 200 on reuse.
        if dotted.endswith("checkout.proceed_to_payment"):
            reuse = captured.get("proceed_to_payment.reused")
            if reuse:
                statuses["200"] = {
                    "description": "Existing open obligation reused",
                    "content": {"application/json": {
                        "schema": {"$ref": "#/components/schemas/Success"},
                        "example": {k: v for k, v in reuse.items()
                                    if k != "__http_status__"}}}}

        if error_key and error_key in captured:
            body = captured[error_key]
            statuses[str(body["__http_status__"])] = {
                "description": "Error envelope",
                "content": {"application/json": {
                    "schema": {"$ref": "#/components/schemas/Error"},
                    "example": {k: v for k, v in body.items()
                                if k != "__http_status__"}}}}

        op = {
            "summary": ep["summary"] or dotted.rsplit(".", 1)[-1],
            "operationId": dotted,
            "tags": [dotted.split(".")[0]],
            "security": [] if ep["guest"] else [{"sessionCookie": []}],
            "responses": statuses,
        }

        if dotted in PAYMENT_NOTES:
            op["description"] = "\n".join(f"- {n}" for n in PAYMENT_NOTES[dotted])

        if verb == "post":
            op["requestBody"] = {"required": bool(ep["params"]),
                                 "content": {"application/json": {"schema": {
                "type": "object",
                "required": [p["name"] for p in ep["params"] if p["required"]],
                "properties": {
                    p["name"]: {"description": f"default: {p['default']!r}"}
                    for p in ep["params"]},
            }}}}
            if not ep["guest"]:
                op["parameters"] = [{
                    "name": "X-Frappe-CSRF-Token", "in": "header", "required": True,
                    "schema": {"type": "string"},
                    "description": "Frappe CSRF token from login or get_session_context.",
                }]
        else:
            op["parameters"] = [
                {"name": p["name"], "in": "query", "required": p["required"],
                 "schema": {"type": "string"}}
                for p in ep["params"]
            ]

        paths[f"/api/method/{dotted}"] = {verb: op}

    return {
        "openapi": "3.1.0",
        "info": {
            "title": "YOB Storefront & Auth API",
            "version": "2.0.0",
            "description": (
                "Frappe RPC-style API. Every response is wrapped by Frappe in an "
                "outer `message` object; the inner body is the YOB envelope "
                "(`data` plus optional `notice`/`meta` on success, `errors[]` on "
                "failure). There is NO `success` boolean: branch on HTTP status, "
                "then on `errors[0].code`.\n\n"
                "Version 2.0.0 reflects the Payment Lifecycle Phase 2B backend. "
                "The payment contract changed materially: a Payment Request is an "
                "immutable obligation, `get_checkout_data` serves both Cart-backed "
                "and Sales-Order-backed sources, and `process_payment` commits the "
                "cart to exactly one Draft Sales Order before contacting any "
                "provider.\n\n"
                "CSRF is Frappe's own: non-GET authenticated requests need "
                "`X-Frappe-CSRF-Token`. Authenticated calls must traverse the edge "
                "proxy that sets `X-YOB-Original-Host`. Guest payment endpoints "
                "are authorized by the checkout token or by Razorpay's HMAC "
                "signature and need no session."
            ),
        },
        "servers": [{"url": BASE_URL}],
        "components": {
            "securitySchemes": {
                "sessionCookie": {"type": "apiKey", "in": "cookie", "name": "sid"}},
            "schemas": {
                "Success": {"type": "object", "properties": {"message": {
                    "type": "object",
                    "required": ["data"],
                    "properties": {"data": {}, "notice": {"type": "string"},
                                   "meta": {"type": "object"}}}}},
                "Error": {"type": "object", "properties": {"message": {
                    "type": "object",
                    "required": ["errors"],
                    "properties": {"errors": {"type": "array", "items": {
                        "type": "object",
                        "required": ["code", "detail"],
                        "properties": {
                            "code": {"type": "string"},
                            "detail": {"type": "string"},
                            "field": {"type": "string"},
                            "details": {"type": "object"}}}}}}}},
            },
        },
        "paths": paths,
    }


# =========================================================
# POSTMAN
# =========================================================

POSTMAN_BODIES = {
    "yob_storefront.api.payment.process_payment": {
        "Pay Later": {"token": "{{checkout_token}}", "payment_method": "Pay Later"},
        "Razorpay": {"token": "{{checkout_token}}", "payment_method": "Razorpay"},
    },
    "yob_storefront.api.payment.verify_payment": {
        None: {"razorpay_order_id": "{{razorpay_order_id}}",
               "razorpay_payment_id": "{{razorpay_payment_id}}",
               "razorpay_signature": "{{razorpay_signature}}"},
    },
}

POSTMAN_QUERY = {
    "yob_storefront.api.payment.get_checkout_data": {"token": "{{checkout_token}}"},
    "yob_storefront.api.payment_method.get_payment_methods": {"order_amount": "500"},
}


def build_postman(eps):
    items = []

    for ep in eps:
        dotted = ep["path"]
        verb = "POST" if "POST" in ep["methods"] else "GET"

        variants = POSTMAN_BODIES.get(dotted, {None: None})

        for label, body in variants.items():
            headers = [{"key": "Content-Type", "value": "application/json"}]
            if verb == "POST" and not ep["guest"]:
                headers.append({"key": "X-Frappe-CSRF-Token", "value": "{{csrf_token}}"})

            query = POSTMAN_QUERY.get(dotted, {})
            raw = f"{{{{base_url}}}}/api/method/{dotted}"
            if query:
                raw += "?" + "&".join(f"{k}={v}" for k, v in query.items())

            req = {
                "method": verb,
                "header": headers,
                "url": {"raw": raw, "host": ["{{base_url}}"],
                        "path": ["api", "method", dotted],
                        "query": [{"key": k, "value": v} for k, v in query.items()]},
            }

            if verb == "POST":
                payload = body if body is not None else {
                    p["name"]: "" for p in ep["params"]}
                req["body"] = {"mode": "raw", "raw": json.dumps(payload, indent=2)}

            items.append({"name": dotted + (f" ({label})" if label else ""),
                          "request": req})

    return {
        "info": {
            "name": "YOB Storefront & Auth API (Phase 2B)",
            "description": (
                "Session: run login_with_password first, keep the sid cookie, and "
                "put the returned csrf_token into the {{csrf_token}} variable.\n\n"
                "No real credentials, session ids, checkout tokens or Razorpay "
                "secrets are stored in this collection -- every such value is a "
                "placeholder variable you fill in locally."
            ),
            "schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json",
        },
        "variable": [
            {"key": "base_url", "value": BASE_URL},
            {"key": "csrf_token", "value": "", "description": "From login response."},
            {"key": "checkout_token", "value": "",
             "description": "From proceed_to_payment `data.token`. A live bearer credential -- never commit a real one."},
            {"key": "razorpay_order_id", "value": ""},
            {"key": "razorpay_payment_id", "value": ""},
            {"key": "razorpay_signature", "value": ""},
        ],
        "item": items,
    }


# =========================================================
# VERIFIED RESPONSES
# =========================================================

PAYMENT_ENTRIES = [
    ("proceed_to_payment", "POST",
     "/api/method/yob_storefront.api.checkout.proceed_to_payment",
     [("created_201", "proceed_to_payment.created"),
      ("reused_200", "proceed_to_payment.reused")]),
    ("get_checkout_data", "GET",
     "/api/method/yob_storefront.api.payment.get_checkout_data",
     [("cart_backed", "get_checkout_data.cart_backed"),
      ("sales_order_backed", "get_checkout_data.sales_order_backed"),
      ("blank_token", "get_checkout_data.blank_token"),
      ("invalid_token", "get_checkout_data.invalid_token"),
      ("expired_token", "get_checkout_data.expired_token"),
      ("stale_cart", "get_checkout_data.stale")]),
    ("process_payment", "POST",
     "/api/method/yob_storefront.api.payment.process_payment",
     [("paylater", "process_payment.paylater"),
      ("razorpay", "process_payment.razorpay"),
      ("missing_method", "process_payment.missing_method"),
      ("unknown_method", "process_payment.unknown_method"),
      ("ineligible_method", "process_payment.ineligible_method"),
      ("stale_cart", "process_payment.stale"),
      ("provider_failure_after_commitment", "process_payment.provider_failure")]),
    ("verify_payment", "POST",
     "/api/method/yob_storefront.api.payment.verify_payment",
     [("success", "verify_payment.success"),
      ("idempotent_retry", "verify_payment.idempotent_retry"),
      ("bad_signature", "verify_payment.bad_signature"),
      ("missing_field", "verify_payment.missing_field"),
      ("unknown_order", "verify_payment.unknown_order")]),
    ("get_payment_methods", "GET",
     "/api/method/yob_storefront.api.payment_method.get_payment_methods",
     [("eligible", "get_payment_methods")]),
]


def build_verified(captured):
    previous = json.loads(PREVIOUS.read_text()) if PREVIOUS.exists() else {}
    out = dict(previous)

    out["captured_at"] = frappe.utils.today()
    out["reference_version"] = "2.0.0"
    out["backend_phase"] = "Payment Lifecycle Phase 2B"

    out["environment"] = {
        "browser_facing_origin": BASE_URL,
        "edge_proxy": (
            "nginx ~/yob-edge/nginx.conf on :8080, vhost storefront.local, sets "
            "X-YOB-Original-Host and X-Frappe-Site-Name"
        ),
        "frappe_site_for_payment_capture": "test.localhost",
        "frappe_site_for_earlier_wire_capture": "yob.localhost",
        "application_code": "STOREFRONT",
        "data_state": (
            "test.localhost carries seeded demo catalog, customer, contact, "
            "addresses, pricing rule and payment methods; payment contracts were "
            "captured against that data."
        ),
    }

    out["verification_levels"] = {
        "wire": "Observed over HTTP through the edge proxy.",
        "test": (
            "The real endpoint was executed in-process against seeded data, "
            "inside a rolled-back savepoint with frappe.db.commit suppressed and "
            "a deterministic Razorpay fake. Bodies are real envelopes from the "
            "real implementation, but no HTTP round trip and no live provider "
            "were involved."
        ),
        "source": "Read from the implementation; not executed.",
    }

    payment = {}
    for name, method, path, branches in PAYMENT_ENTRIES:
        entry = {
            "verified": "test",
            "method": method,
            "path": path,
            "guest": name in ("get_checkout_data", "process_payment", "verify_payment"),
            "notes": PAYMENT_NOTES.get(
                next(k for k in PAYMENT_NOTES if k.endswith("." + name)), []),
            "responses": {},
        }
        for label, key in branches:
            body = captured.get(key)
            if not body:
                continue
            entry["responses"][label] = {
                "status": body["__http_status__"],
                "body": {k: v for k, v in body.items() if k != "__http_status__"},
            }
        payment[name] = entry

    out["payment"] = payment

    # Keep the old proceed_to_payment stub from drifting alongside the new one.
    out.get("storefront", {}).pop("proceed_to_payment", None)
    out.get("storefront", {}).pop("get_payment_methods", None)

    out["stable_error_codes"] = dict(previous.get("stable_error_codes", {}))
    out["stable_error_codes"]["checkout_payment"] = {
        "checkout_token_invalid": "404 - blank, unknown, or revoked checkout token.",
        "checkout_token_expired": "422 - token recognised but past custom_checkout_expiry.",
        "payment_request_stale": "409 - the cart changed since the obligation was issued; restart checkout.",
        "payment_reference_invalid": "422 - the payment could not be matched to a usable source/order.",
        "payment_method_unsupported": "422 - unknown method, or a known method that is not eligible now.",
        "payment_provider_not_configured": "500 - no Razorpay API key on the server.",
        "payment_provider_error": "500 - provider unreachable AFTER local commitment; details.retryable=true, details.sales_order present, order NOT rolled back.",
        "payment_already_processed": "409 - a different payment arrived for an already-settled obligation.",
        "payment_signature_invalid": "422 - Razorpay HMAC verification failed.",
        "payment_verification_failed": "500 - signature verification could not be completed.",
        "payment_not_captured": "422 - provider order/payment is not in a paid/captured state.",
        "payment_amount_mismatch": "409 - provider amount does not match the immutable obligation.",
        "payment_currency_mismatch": "409 - provider currency does not match the obligation.",
        "cart_not_found": "404 - no open cart for proceed_to_payment.",
        "cart_empty": "422 - proceed_to_payment with an empty cart.",
        "contact_required": "422 - field=contact_person.",
        "billing_address_required": "422 - field=billing_address.",
        "shipping_address_required": "422 - field=shipping_address, shippable carts only.",
        "validation_failed": "422 - a required request field was missing.",
        "order_not_found": "404 - the referenced Sales Order no longer exists.",
        "customer_not_found": "404 - the customer behind the checkout link no longer exists.",
    }
    out["stable_error_codes"]["source"] = (
        "yob_storefront/api/response.py plus the Phase 2B payment capture; "
        "every code above appears in current source or captured responses."
    )

    return out


README = """# YOB frontend API reference — live verification capture

**Reference version 2.0.0 — regenerated for backend Payment Lifecycle Phase 2B.**

`verified-responses.json` holds sanitized responses produced by the current
backend. It exists so SPA network, session and mock code can be typed against
observed behaviour rather than against the OpenAPI examples alone.

## Capture

| | |
|---|---|
| Capture date | {date} |
| Backend phase | Payment Lifecycle Phase 2B |
| Payment capture site | `test.localhost` (seeded demo data, fully migrated) |
| Earlier non-payment wire capture | `yob.localhost` via the `:8080` edge proxy |
| Application code | `STOREFRONT` |

The payment capture site was confirmed migrated for every current payment custom
field before capture: `custom_checkout_token` (Data, **UNIQUE**),
`custom_checkout_expiry`, `custom_source_fingerprint`, `custom_razorpay_order_id`,
`custom_razorpay_payment_id`.

## Verification levels

Each entry carries `"verified"`, and the three values mean different things:

- **`wire`** — observed over HTTP through the edge proxy.
- **`test`** — the real endpoint was executed in-process against seeded data,
  inside a rolled-back savepoint with `frappe.db.commit` suppressed and a
  deterministic Razorpay fake. The bodies are real envelopes from the real
  implementation, but **no HTTP round trip and no live provider were involved.**
- **`source`** — read from the implementation; not executed.

### Why payment endpoints are `test`, not `wire`

Every payment endpoint mutates durable business state: a real call creates
Payment Requests and Sales Orders, leaves the Cart Ordered, and contacts
Razorpay. Running those against a site merely to populate documentation is not
acceptable, so they were executed under the isolation described above instead.
The site was verified byte-for-byte unchanged afterwards — no Payment Requests,
Sales Orders, Ordered Carts, API keys, provider orders or payment logs left
behind.

This is a deliberate accuracy choice: these responses are **not** labelled
`wire`, because no HTTP request was made.

## Payment lifecycle the SPA must model

A Payment Request is an **immutable obligation**. Its amount and currency never
change after issue.

```
proceed_to_payment   ->  Payment Request backed by a CART
process_payment      ->  commits ONE Draft Sales Order
                     ->  Payment Request now backed by that SALES ORDER
verify_payment       ->  settles that exact Sales Order
```

Consequences for the frontend:

- `get_checkout_data` returns **two different shapes**. Branch on
  `data.source_doctype` (`"Cart"` or `"Sales Order"`). In the Sales Order shape
  `billing_address`/`shipping_address` are **name strings**, not objects, and
  `items[]` is flat.
- After the obligation becomes Sales-Order-backed, **the Cart is no longer
  payment truth.** It is not read or revalidated, and later cart edits cannot
  invalidate the committed payment.
- The checkout token is **not** revoked when the source moves Cart → Sales
  Order. `/payment/:token` keeps working across refreshes and retries, and a Pay
  Later order stays payable later. It *is* revoked once the payment settles.
- `amount` is in normal business units everywhere **except** the Razorpay
  `process_payment` response, where it is in provider units (paise:
  `13500` == INR 135.00) for direct handoff to the Razorpay widget.
- A provider failure after commitment returns `payment_provider_error` with
  `details.retryable = true` and `details.sales_order`. **The order was not
  rolled back** — offer a retry rather than reporting a failed order.

`/payment/:token` is a **public SPA route**: the payment endpoints are
guest-accessible and require no session.

## Sanitization

`csrf_token`, `sid`, checkout `token`, `payment_url` token segment,
`razorpay_key` and `razorpay_signature` are replaced with `<REDACTED>`. Checkout
tokens are live bearer credentials and are never stored here. Razorpay order and
payment ids in the examples are fake (`order_EXAMPLE0001`, `pay_EXAMPLE0001`)
and were produced by the deterministic stub.

Frappe traceback payloads (`exc`, `_server_messages`) are truncated to a marker
— see `errors.raw_frappe_*`, which record the *shape* the frontend must
tolerate, not the text.

## Still pending

**Real Razorpay Test-Mode verification.** Everything provider-facing was proven
against a deterministic fake that enforces Razorpay's documented receipt rules.
Not yet confirmed against the live sandbox: the 40-character receipt accepted on
the wire, the exact duplicate-receipt error class, `order.all({{"receipt": …}})`
filtering, and live signature verification. The response *contract* the SPA
consumes is unaffected by these, but the recovery paths are not wire-proven.

## Superseded statements

Earlier revisions of this file said the bench had no catalog/order/address data
and that `proceed_to_payment` success could not be captured. Both are obsolete:
`test.localhost` is seeded, and every payment branch above was executed.
"""


def run():
    site = frappe.local.site
    if site not in ALLOWED_SITES:
        frappe.throw(f"build_frontend_reference refuses to run on '{site}'.")

    captured = _captured()
    eps = endpoints()

    (BUILD / "live").mkdir(parents=True, exist_ok=True)

    (BUILD / "openapi.json").write_text(
        json.dumps(build_openapi(eps, captured), indent=2))
    (BUILD / "postman_collection.json").write_text(
        json.dumps(build_postman(eps), indent=2))
    (BUILD / "live" / "verified-responses.json").write_text(
        json.dumps(build_verified(captured), indent=2))
    (BUILD / "live" / "README.md").write_text(
        README.format(date=frappe.utils.today()))

    print(f"endpoints documented : {len(eps)}")
    print(f"payment branches     : {len(captured)}")
    print(f"written to           : {BUILD}")
    return [e["path"] for e in eps]
